### ISSUE TITLE
Error: undecalred indentifier: 'expr'

### ISSUE THREAD

**Issue by retsyo** [PMunch/wxnim#11]
latest nim and your wxnim are used, the nim.cfg is removed
```
/r/PMunch-wxnim/examples/purewx
$ nim cpp example1.nim
```
says
`PMunch-wxnim\private\objecti.nim(6. 40) Error: undecalred indentifier: 'expr'`

**Comment by PMunch** [comment]
It works with 0.17.2, but to fix this issue should just be a case of changing `expr` to `untyped`

**Comment by PMunch** [comment]
Removed various things that was removed in 0.18.0, so it now works on that. Trying to also make it work on devel now, but I'll close this issue.

**Comment by PMunch** [comment]
It should work fine on devel now
